services:
  leetnote-backend:
    image: tanqng/leetnote-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
    restart: unless-stopped